export const SONGS = [
  {
    id: 1,
    artist: "Gilbert O'Sullivan",
    name: "Alone Again (Naturally)",
    imgUrl: "./img/gilbert-osullivan.jpg",
    audioUrl: "./music/gilbert-osullivan.mp3",
    isFavorite: true,
  },
  {
    id: 2,
    artist: "B.J. Thomas",
    name: "Raindrops Keep Falling On My Head",
    imgUrl: "./img/bj-thomas.jpg",
    audioUrl: "./music/bj-thomas.mp3",
    isFavorite: true,
  },
  {
    id: 3,
    artist: "The Carpenters",
    name: "Close To You",
    imgUrl: "./img/Close-To-You.jpg",
    audioUrl: "./music/Close-To-You.mp3",
    isFavorite: true,
  },
  {
    id: 4,
    artist: "Elvis Presley",
    name: "Can't Help Falling In Love",
    imgUrl: "./img/elvis-presley.jpg",
    audioUrl: "./music/elvis-presley.mp3",
    isFavorite: true,
  },
  {
    id: 5,
    artist: "Roy Orbison",
    name: "Oh, Pretty Woman",
    imgUrl: "./img/roy-orbison.jpg",
    audioUrl: "./music/roy-orbison.mp3",
    isFavorite: true,
  },
  {
    id: 6,
    artist: "Morten Harket",
    name: "Can't Take My Eyes Off You",
    imgUrl: "./img/morten-harket.jpg",
    audioUrl: "./music/morten-harket.mp3",
    isFavorite: true,
  },
  {
    id: 7,
    artist: "Fools Garden",
    name: "Lemon Tree",
    imgUrl: "./img/lemon-tree.jpg",
    audioUrl: "./music/lemon-tree.mp3",
    isFavorite: true,
  },
  {
    id: 8,
    artist: "Sarah Vaughan",
    name: "A Lover's Concerto",
    imgUrl: "./img/a-lovers-concerto.jpg",
    audioUrl: "./music/a-lovers-concerto.mp3",
    isFavorite: true,
  },
  {
    id: 9,
    artist: "Ron Dante, The Archies",
    name: "Sugar Sugar",
    imgUrl: "./img/sugar-sugar.jpg",
    audioUrl: "./music/sugar-sugar.mp3",
    isFavorite: true,
  },
  {
    id: 10,
    artist: "Barry Manilow",
    name: "Can't Smile Without You",
    imgUrl: "./img/barry-manilow.jpg",
    audioUrl: "./music/barry-manilow.mp3",
    isFavorite: true,
  },
  {
    id: 11,
    artist: "The Carpenters",
    name: "Yesterday Once More",
    imgUrl: "./img/carpenters.jpg",
    audioUrl: "./music/carpenters.mp3",
    isFavorite: true,
  },
  {
    id: 12,
    artist: "Earth, Wind & Fire",
    name: "Boogie Wonderland",
    imgUrl: "./img/boogie-wonderland.jpg",
    audioUrl: "./music/boogie-wonderland.mp3",
    isFavorite: true,
  },
  {
    id: 13,
    artist: "Westlife",
    name: "Nothing's Going to Change My Love For You",
    imgUrl: "./img/westlife.jpg",
    audioUrl: "./music/westlife.mp3",
    isFavorite: true,
  },
  {
    id: 14,
    artist: "Trademark",
    name: "Only Love",
    imgUrl: "./img/only-love.jpg",
    audioUrl: "./music/only-love.mp3",
    isFavorite: true,
  },
  {
    id: 15,
    artist: "Earth, Wind & Fire",
    name: "September",
    imgUrl: "./img/earth-wind&fire.jpg",
    audioUrl: "./music/earth-wind&fire.mp3",
    isFavorite: true,
  },
  {
    id: 16,
    artist: "Bobby Caldwell",
    name: "What You Won’t Do For Love",
    imgUrl: "./img/bobby-caldwell.jpg",
    audioUrl: "./music/bobby-caldwell.mp3",
    isFavorite: true,
  },
  {
    id: 17,
    artist: "Oasis",
    name: "Don't Look Back In Anger",
    imgUrl: "./img/oasis.jpg",
    audioUrl: "./music/oasis.mp3",
    isFavorite: true,
  },
  {
    id: 18,
    artist: "Stevie Wonder",
    name: "Isn't She Lovely",
    imgUrl: "./img/stevie-wonder.jpg",
    audioUrl: "./music/stevie-wonder.mp3",
    isFavorite: true,
  },
  {
    id: 19,
    artist: "King Harvest",
    name: "A Little Bit Like Magic",
    imgUrl: "./img/king-harvest.jpg",
    audioUrl: "./music/king-harvest.mp3",
    isFavorite: true,
  },
  {
    id: 20,
    artist: "John Denver",
    name: "Country Road",
    imgUrl: "./img/john-denver.jpg",
    audioUrl: "./music/john-denver.mp3",
    isFavorite: true,
  },
  {
    id: 21,
    artist: "Ben E. King",
    name: "Stand By Me",
    imgUrl: "./img/ben-e-king.jpg",
    audioUrl: "./music/ben-e-king.mp3",
    isFavorite: true,
  },
];
